version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: tvonline
    restart: always
    volumes:
      - tvonline-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tvonline

volumes:
  tvonline-disk: